### ISSUE TITLE
טופס צור קשר

### ISSUE THREAD

**Issue by emrib** [hasadna/TreeBase#11]
האם ניתן טקטסט כפתורים בעברית? לאן זה מגיע? שלחתי פנייה ולא קיבלתי למייל שלי

**Comment by akariv** [comment]
עדכנתי כך שיגיע לכתובת המייל החדשה.
לא הבנתי על איזה טקסט כפתורים מדובר @emrib

**Comment by emrib** [comment]
זה בסדר ככה
