### ISSUE TITLE
הוספת קישור לממשק צפייה מעמוד נחיתה

### ISSUE THREAD

**Issue by emrib** [hasadna/TreeBase#24]
בסרגל העליון לכתוב "ממשק צפייה" משמאל לאודות ומימין למזעץ:  יפתח דף חדש בדפדפן עם אתר הצפייה

**Comment by akariv** [comment]
איפה?
מה הטקסט?

**Comment by emrib** [comment]
מבקש להוסיף בלוק של ממשק הצפייה מעל המזעץ. הוא יהיה דומה בלייאוט לבלוק של "קצב הצמיחה שלנו" 
במקום תמונה יהיה צילום מסך של המערכת (האם ניתן גלריה?)
הטקסט יהיה דומה בפורמט ובאורך שלו (ללא חיבור נתונים חיים)



![Image](https://github.com/hasadna/TreeBase/assets/76155903/5523d92c-bdb4-4060-93f9-a0b4aeebb9ee)

**Comment by akariv** [comment]
מה הטקסט @emrib ?

**Comment by akariv** [comment]
הוספתי בינתיים טקסט זמני, מוזמן להציע שינויים.
