### ISSUE TITLE
הוספת מדדים לעמוד נחיתה

### ISSUE THREAD

**Issue by emrib** [hasadna/TreeBase#25]
מדדים:

מספר עצים (מזעץ) במאגר
ממוצע אחוז כיסוי חופות לרשות 
אחוז רשויות עם יותר מ-10% כיסוי חופות  
אחוז רשויות ששיתפו סקר עצים

כרגע כטקסט פשוט ללא עיצוב בגלל לוחות הזמנים

**Comment by akariv** [comment]
איזה מדדים?
האם יש עיצוב?

**Comment by emrib** [comment]
תכף

**Comment by emrib** [comment]
עידכנתי בתגובה הראשנה @akariv

**Comment by emrib** [comment]
@dorit102  ראי מדדים בתגובה ראשונה
אם מוסכם, אבקש מהילה שתציע עיצוב

**Comment by emrib** [comment]
עידכנתי תגובה ראשונה- אושר עם דורית @akariv

**Comment by akariv** [comment]
@emrib ככלל עדיף לא לערוך תגובות אלא פשוט להוסיף חדשות (כשמתחילים לערוך זה מהר מאוד נהיה לא קריא)

2. מניח שתרצו גם לשנות את הקופי באתר, עדכן אותי אם כן.
