### ISSUE TITLE
מימוש ראשון של דף הנחיתה

### ISSUE THREAD

**Issue by akariv** [hasadna/TreeBase#3]

**Comment by akariv** [comment]
https://hasadna.github.io/treebase-landing-page/

**Comment by emrib** [comment]
תודה
1. הוספתי בפיגמה קישורים ללוגיים של השותפים. נראה להם את האתר בועדת ההיגוי לאיפיון פלטפורמה לניהו להיער העירוני (30/1/23) ולאחר מכן נוכל לעלות לאוויר
2.   תיקייה בדרייב עם רשויות שותפות ולוגיים https://drive.google.com/drive/folders/1PweiAnnKSy3pzXE5z_LHiV5-Jvu89IsR?usp=share_link
4. שלומית תשפר טיפה את הלוגו
5. מזכיר שבהמשך הקרוב אני מקווה נחליף את השאלות במדדים אמיתיים
6. האם ניתן לייצר כתובת מייל לפרויקט (מה העלות) במקום המייל שלי, לטובת רשמיות?
7. שלומית היתה חולה. גירסא אחרונה שלה תהיה השבוע ועם זה נסיים
8. לשנות ל"היער הדיגיטלי" במקום "יער עירוני"

**Comment by akariv** [comment]
- כתובת מייל תחת hasadna זה ללא עלות למיטב ידיעתי, דורית יכולה לעשות את זה.
- אעדכן את הקישורים.
- מבקש שכל שינוי לעיצוב שמבוצע בפיגמה יתועד (אפשר על ידי השארת הערה שם
במקום הרלוונטי) ע״מ שאדע להטמיע את השינויים שהוכנסו למימוש הקיים.

**Comment by emrib** [comment]
1.   מה שניתן להשלים ולהטמיע בגדר שינויים קטנים  מהפיגמה: פונט למשל
2. לוגיים רשויות https://drive.google.com/drive/folders/1PweiAnnKSy3pzXE5z_LHiV5-Jvu89IsR
3. לוגו פרויקט + סימבולים של מזעץ נעדכן בעצמנו
