### ISSUE TITLE
לוגו יער עירוני דיגיטלי

### ISSUE THREAD

**Issue by emrib** [hasadna/TreeBase#7]
להחליף לוגו קיים ולשנות כיתוב ליער דיגיטלי לא היער הדיגיטלי (גם בכותרת ובתגית בדפדפן). אמרי ביקש מרות (מתנדבת) לעזור לעצב לוגו כך שיהיה קצת יותר ברור שזה עץ ולא ענן. מחכה לקבל ממנה תוצר

link: https://drive.google.com/drive/folders/12gzZ1oWv36BP7QmmtkVv8mThDl0S_XaD

**Comment by akariv** [comment]
נראה לי שזה לא הכיתוב שנבחר בסוף.
יש כבר לוגו חדש או שעדיין מחכים לרות?

**Comment by emrib** [comment]
דורית אישרה שזה השם והלוגו בוואטסאפ שלנו @akariv

**Comment by akariv** [comment]
כלומר לשנות כיתוב ליער דיגיטלי?
הלוגו נמצא בפיגמה? (מה שבדרייב הוא תמונה ולא לוגו וקטורי)

**Comment by emrib** [comment]
יותר מזה.. "יער עירוני דיגיטלי" לבקשת אנדי
ביקשתי מרות וקטורי

**Comment by akariv** [comment]
אחלה, זה מה שחשבתי.... פשוט שונה ממה שכתבת קודם.
